1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.

In [ ]:
import numpy as np
arr = np.arange(6)
print(arr)
print(arr.dtype)
# Output will be: [0 1 2 3 4 5] and dtype('int64') (or int32 depending on system)

2. Given a NumPy array 'arr', check if its data type is float64. $arr=np.array([1.5,2.6,3.7])$

In [ ]:
import numpy as np
arr = np.array([1.5, 2.6, 3.7])
is_float64 = (arr.dtype == np.float64)
print(is_float64)
# Output will be: True

3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.

In [ ]:
import numpy as np
arr = np.array([1 + 2j, 3 - 4j, 5 + 0j], dtype=np.complex128)
print(arr)
print(arr.dtype)
# Output will be: [1.+2.j 3.-4.j 5.+0.j] and dtype('complex128')

4. Convert an existing NumPy array 'arr' of integers to float32 data type.

In [ ]:
import numpy as np
arr_int = np.array([1, 2, 3, 4])
arr_float32 = arr_int.astype(np.float32)
print(arr_float32)
print(arr_float32.dtype)
# Output will be: [1. 2. 3. 4.] and dtype('float32')

5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.

In [ ]:
import numpy as np
arr_float64 = np.array([1.23456789, 2.34567890], dtype=np.float64)
arr_float32 = arr_float64.astype(np.float32)
print(arr_float32)
print(arr_float32.dtype)
# Output will show reduced precision: [1.2345679 2.3456789] and dtype('float32')

6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type.

In [ ]:
import numpy as np
def array_attributes(arr):
    return arr.shape, arr.size, arr.dtype

arr_ex = np.array([[1, 2], [3, 4], [5, 6]])
shape, size, dtype = array_attributes(arr_ex)
print(f"Shape: {shape}, Size: {size}, Data Type: {dtype}")
# Output: Shape: (3, 2), Size: 6, Data Type: int64

7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.

In [ ]:
import numpy as np
def array_dimension(arr):
    return arr.ndim

arr_ex_2d = np.array([[1, 2], [3, 4]])
print(f"Dimension: {array_dimension(arr_ex_2d)}")
# Output: Dimension: 2

arr_ex_3d = np.zeros((2, 3, 4))
print(f"Dimension: {array_dimension(arr_ex_3d)}")
# Output: Dimension: 3

8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes.

In [ ]:
import numpy as np
def item_size_info(arr):
    item_size = arr.itemsize
    total_size = arr.nbytes
    return item_size, total_size

arr_ex = np.array([1, 2, 3], dtype=np.int32) # int32 is 4 bytes
item_s, total_s = item_size_info(arr_ex)
print(f"Item Size (bytes): {item_s}, Total Size (bytes): {total_s}")
# Output: Item Size (bytes): 4, Total Size (bytes): 12 (4 * 3 elements)

9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array.

In [ ]:
import numpy as np
def array_strides(arr):
    return arr.strides

arr_ex = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int64) # int64 is 8 bytes
print(f"Strides: {array_strides(arr_ex)}")
# Output: Strides: (24, 8) -> 24 bytes to move to the next row (3 * 8), 8 bytes to move to the next column (1 * 8)

10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array.

In [ ]:
import numpy as np
def shape_stride_relationship(arr):
    return arr.shape, arr.strides

arr_ex = np.array([[1, 2], [3, 4], [5, 6]], dtype=np.int32) # int32 is 4 bytes
shape, strides = shape_stride_relationship(arr_ex)
print(f"Shape: {shape}, Strides: {strides}")
# Output: Shape: (3, 2), Strides: (8, 4) -> 8 bytes to next row (2 * 4), 4 bytes to next column (1 * 4)

11. Create a function create_zeros_array that takes an integer n as input and returns a NumPy array of zeros with n elements.

In [ ]:
import numpy as np
def create_zeros_array(n):
    return np.zeros(n)

arr_zeros = create_zeros_array(5)
print(arr_zeros)
# Output: [0. 0. 0. 0. 0.]

12. Write a function create_ones_matrix that takes integers rows and cols as inputs and generates a 2D NumPy array filled with ones of size rows x cols.

In [ ]:
import numpy as np
def create_ones_matrix(rows, cols):
    return np.ones((rows, cols))

matrix_ones = create_ones_matrix(2, 3)
print(matrix_ones)
# Output: [[1. 1. 1.]
#          [1. 1. 1.]]

13. Write a function generate_range_array that takes three integers start, stop, and step as arguments and creates a NumPy array with a range starting from start, ending at stop (exclusive), and with the specified step.

In [ ]:
import numpy as np
def generate_range_array(start, stop, step):
    return np.arange(start, stop, step)

arr_range = generate_range_array(10, 30, 5)
print(arr_range)
# Output: [10 15 20 25]

14. Design a function generate_linear_space that takes two floats start, stop, and an integer num as arguments and generates a NumPy array with num equally spaced values between start and stop (inclusive).

In [ ]:
import numpy as np
def generate_linear_space(start, stop, num):
    return np.linspace(start, stop, num)

arr_linear = generate_linear_space(0, 1, 5)
print(arr_linear)
# Output: [0.   0.25 0.5  0.75 1.  ]

15. Create a function create_identity_matrix that takes an integer n as input and generates a square identity matrix of size $n \times n$ using numpy.eye. 17

In [ ]:
import numpy as np
def create_identity_matrix(n):
    return np.eye(n)

id_matrix = create_identity_matrix(3)
print(id_matrix)
# Output: [[1. 0. 0.]
#          [0. 1. 0.]
#          [0. 0. 1.]]

16. Write a function that takes a Python list and converts it into a NumPy array.

In [ ]:
import numpy as np
def list_to_numpy_array(py_list):
    return np.array(py_list)

my_list = [10, 20, 30]
np_array = list_to_numpy_array(my_list)
print(np_array)
print(type(np_array))
# Output: [10 20 30] and <class 'numpy.ndarray'>

17. Create a NumPy array and demonstrate the use of numpy.view to create a new array object with the same data.

In [ ]:
import numpy as np
original_arr = np.array([1, 2, 3, 4])
# Create a view
view_arr = original_arr.view()

# Check if they share the same data (True)
print(f"Data shared? {np.shares_memory(original_arr, view_arr)}")

# Modify the view
view_arr[0] = 99

# Check if the original array is modified (Yes, because it's a view)
print(f"Original array after modifying view: {original_arr}")
print(f"View array: {view_arr}")
# Output: Data shared? True
# Output: Original array after modifying view: [99  2  3  4]
# Output: View array: [99  2  3  4]

18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.

In [ ]:
import numpy as np
def concatenate_arrays(arr1, arr2, axis=0):
    return np.concatenate((arr1, arr2), axis=axis)

arr_a = np.array([[1, 2], [3, 4]])
arr_b = np.array([[5, 6], [7, 8]])

# Concatenate along axis=0 (rows)
concat_rows = concatenate_arrays(arr_a, arr_b, axis=0)
print("Concatenated along axis 0:\n", concat_rows)
# Output: [[1 2]
#          [3 4]
#          [5 6]
#          [7 8]]

# Concatenate along axis=1 (columns)
concat_cols = concatenate_arrays(arr_a, arr_b, axis=1)
print("Concatenated along axis 1:\n", concat_cols)
# Output: [[1 2 5 6]
#          [3 4 7 8]]

19. Create two NumPy arrays with different shapes and concatenate them horizontally using numpy.concatenate.  Note: numpy.concatenate requires the arrays to have matching shapes along the axis not being concatenated. For horizontal concatenation (axis=1), the number of rows (axis=0) must match.

In [ ]:
import numpy as np
arr1 = np.array([[1, 2], [3, 4]]) # Shape (2, 2)
arr2 = np.array([[5, 6, 7], [8, 9, 10]]) # Shape (2, 3)

# Concatenate horizontally (axis=1). Rows match (2).
h_concat = np.concatenate((arr1, arr2), axis=1)
print("Horizontal Concatenation:\n", h_concat)
# Output: [[ 1  2  5  6  7]
#          [ 3  4  8  9 10]]

20. Write a function that vertically stacks multiple NumPy arrays given as a list.

In [ ]:
import numpy as np
def vertical_stack_arrays(array_list):
    return np.vstack(array_list)

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.array([7, 8, 9])

v_stacked = vertical_stack_arrays([arr1, arr2, arr3])
print("Vertically Stacked:\n", v_stacked)
# Output: [[1 2 3]
#          [4 5 6]
#          [7 8 9]]

21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size.

In [ ]:
import numpy as np
def concat_arrays_q48(arr1, arr2, axis=0):
    return np.concatenate((arr1, arr2), axis=axis)

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

# Concatenate along axis=0 (default)
result_0 = concat_arrays_q48(array1, array2, axis=0)
print("Concatenated (axis=0):\n", result_0)
# Output: [[1 2]
#          [3 4]
#          [5 6]
#          [7 8]]

22. Create a function that takes a matrix as input and returns the flattened array. 25$input\_matrix=np.array([[1,2,3],[4,5,6]]).

In [ ]:
import numpy as np
def flatten_matrix(matrix):
    return matrix.flatten()

input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
flattened_array = flatten_matrix(input_matrix)
print(f"Flattened array: {flattened_array}")

23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).

In [ ]:
import numpy as np
def concat_arrays(arr1, arr2, axis=0):
    return np.concatenate((arr1, arr2), axis=axis)

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

result = concat_arrays(array1, array2, axis=0)
print("Concatenated along axis 0:\n", result)

24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values
are random integers between 1 and 100.

In [ ]:
import numpy as np
def split_array(arr, num_splits, axis=0):
    return np.split(arr, num_splits, axis=axis)

original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

split_rows = split_array(original_array, 3, axis=0)
print("Split along axis 0 (rows):", split_rows)

25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros. Use NumPy operations within the Pandas DataFrame.

In [ ]:
import numpy as np
def insert_and_delete(arr, ins_idx, ins_val, del_idx):
    # 1. Insert elements
    arr_inserted = np.insert(arr, ins_idx, ins_val)

    # 2. Delete elements from the inserted array
    arr_final = np.delete(arr_inserted, del_idx)
    return arr_inserted, arr_final

original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

arr_ins, arr_del = insert_and_delete(original_array, indices_to_insert, values_to_insert, indices_to_delete)

print(f"Array after insertion: {arr_ins}")
print(f"Array after deletion: {arr_del}")

26. Access the 3rd element from the given NumPy array.
arr = np.array([10, 20, 30, 40, 50])


In [ ]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
element = arr[2]
print(f"3rd element: {element}")

27. Retrieve the element at index (1, 2) from the 2D NumPy array.
.array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
import numpy as np
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
element = arr_2d[1, 2]
print(f"Element at (1, 2): {element}")

28. Using boolean indexing, extract elements greater than 5 from the given NumPy array.
arr = np.array([3, 8, 2, 10, 5, 7])


In [ ]:
import numpy as np
arr = np.array([3, 8, 2, 10, 5, 7])
extracted_elements = arr[arr > 5]
print(f"Elements greater than 5: {extracted_elements}")

29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
extracted_slice = arr[2:6]
print(f"Elements from index 2 to 5: {extracted_slice}")

30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [ ]:
import numpy as np
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

sub_array = arr_2d[:2, 1:3]
print(f"Extracted sub-array:\n{sub_array}")

31. Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array.

In [ ]:
import numpy as np
def extract_elements_by_indices(arr_2d, row_indices, col_indices):
    return arr_2d[row_indices, col_indices]

arr_2d = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
row_indices = np.array([0, 1, 2])
col_indices = np.array([2, 1, 0])

# Extracts (0, 2)=30, (1, 1)=50, (2, 0)=70
extracted = extract_elements_by_indices(arr_2d, row_indices, col_indices)
print(f"Extracted elements: {extracted}")

32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing.

In [ ]:
import numpy as np
def filter_by_threshold(arr, threshold):
    return arr[arr > threshold]

arr = np.array([1, 5, 10, 15, 20])
threshold = 8
filtered = filter_by_threshold(arr, threshold)
print(f"Filtered elements (> {threshold}): {filtered}")

33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension.


In [ ]:
import numpy as np
def extract_3d_elements(arr_3d, dim0_indices, dim1_indices, dim2_indices):
    return arr_3d[dim0_indices, dim1_indices, dim2_indices]

arr_3d = np.arange(24).reshape(2, 3, 4) # Shape (2, 3, 4)
# Extracts elements at (0, 0, 0) and (1, 2, 3)
d0_idx = np.array([0, 1])
d1_idx = np.array([0, 2])
d2_idx = np.array([0, 3])

extracted = extract_3d_elements(arr_3d, d0_idx, d1_idx, d2_idx)
print(f"Extracted elements: {extracted}")
# Output: [ 0 23]

34. Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.

In [ ]:
import numpy as np
def filter_by_two_conditions(arr, cond1, cond2):
    return arr[(cond1) & (cond2)]

arr = np.array([10, 20, 30, 40, 50])
# Condition 1: element > 20, Condition 2: element <= 40
cond1 = (arr > 20)
cond2 = (arr <= 40)

filtered = filter_by_two_conditions(arr, cond1, cond2)
print(f"Elements > 20 AND <= 40: {filtered}")

35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.

In [ ]:
import numpy as np
def extract_elements_by_rc_indices(arr_2d, row_indices, col_indices):
    return arr_2d[row_indices, col_indices]

arr_2d = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
row_indices = np.array([0, 2, 1])
col_indices = np.array([1, 0, 2])

# Extracts (0, 1)=20, (2, 0)=70, (1, 2)=60
extracted = extract_elements_by_rc_indices(arr_2d, row_indices, col_indices)
print(f"Extracted elements: {extracted}")

36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.


In [ ]:
import numpy as np
arr = np.arange(1, 10).reshape(3, 3)

result = arr + 5
print(f"Result (arr + 5):\n{result}")

37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element in arr1 using NumPy broadcasting.


In [ ]:
import numpy as np
# Reshaping arr1 to (3, 1) for broadcasting across the columns of arr2
arr1 = np.array([1, 2, 3]).reshape(3, 1) # Shape (3, 1)
arr2 = np.arange(12).reshape(3, 4) # Shape (3, 4)

result = arr1 * arr2
print(f"Result (arr1 * arr2) with broadcasting:\n{result}")

38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting.

In [ ]:
import numpy as np
# Using a 1D array of shape (3,) to broadcast across the 3 columns of arr2
arr1 = np.array([1, 2, 3]) # Shape (3,)
arr2 = np.arange(12).reshape(4, 3) # Shape (4, 3)

result = arr2 + arr1 # arr1 broadcasts along the rows of arr2
print(f"Result (arr2 + arr1) with broadcasting:\n{result}")

39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.

arr1 broadcasts across columns and arr2 broadcasts across rows, resulting in a (3, 3) array. ```python import numpy as np arr1 = np.array([10, 20, 30]).reshape(3, 1) # (3, 1) arr2 = np.array([1, 2, 3]).reshape(1, 3) # (1, 3)


result = arr1 + arr2 print(f"Result (arr1 + arr2) with broadcasting:\n{result}")

40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting. Handle the shape incompatibility.

In [ ]:
import numpy as np
arr1 = np.arange(6).reshape(2, 3) # (2, 3)

# Create an arr2_compatible array with shape (3, 2)
arr2_compatible = np.arange(6).reshape(3, 2) # (3, 2)

# Matrix multiplication (2, 3) @ (3, 2) = (2, 2)
matrix_product = arr1 @ arr2_compatible
print(f"Matrix Product (arr1 @ arr2_compatible (3, 2)):\n{matrix_product}")

41. Calculate column-wise mean for the given array: 65$arr=np.array([1,2,3],[4,5,6]).

In [ ]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
column_means = np.mean(arr, axis=0)
print(f"Column-wise mean: {column_means}")

42. Find maximum value in each row of the given array: arr = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
row_max = np.max(arr, axis=1)
print(f"Maximum value in each row: {row_max}")

43. For the given array, find indices of maximum value in each column. 69$arr=np.array([[1,2,3],[4,5,6]]).

In [ ]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
max_indices_col = np.argmax(arr, axis=0)
print(f"Indices of maximum value in each column: {max_indices_col}")

44. For the given array, apply custom function to calculate moving sum along rows. 71$arr=np.array([[1,2,3],[4,5,6]]).

In [ ]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
moving_sum_rows = np.cumsum(arr, axis=1)
print(f"Moving sum along rows:\n{moving_sum_rows}")

45. In the given array, check if all elements in each column are even. 73$arr=np.array([[2,4,6],[3,5,7]]).

In [ ]:
import numpy as np
arr = np.array([[2, 4, 6], [3, 5, 7]])
all_even_per_column = np.all(arr % 2 == 0, axis=0)
print(f"Is each column all even: {all_even_per_column}")

46. Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the reshaped matrix.
   original_array = np.array([1, 2, 3, 4, 5, 6])


In [ ]:
import numpy as np
dataset = np.random.randint(1, 1001, size=100)

mean = np.mean(dataset)
median = np.median(dataset)
variance = np.var(dataset)
std_dev = np.std(dataset)

print(f"Dataset Mean: {mean:.2f}")
print(f"Dataset Median: {median:.2f}")
print(f"Dataset Variance: {variance:.2f}")
print(f"Dataset Standard Deviation: {std_dev:.2f}")

47. Create a function that takes a matrix as input and returns the flattened array. input_matrix = np.array([[1, 2, 3], [4, 5, 6]])


In [ ]:
import numpy as np
data = np.random.uniform(1, 100, size=50)

percentile_25 = np.percentile(data, 25)
percentile_75 = np.percentile(data, 75)

print(f"25th Percentile: {percentile_25:.2f}")
print(f"75th Percentile: {percentile_75:.2f}")

48. Write a function that concatenates two given arrays along a specified axis.

array1 = np.array([[1, 2], [3, 4]]),

array2 = np.array([[5, 6], [7, 8]])

In [ ]:
import numpy as np
x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 6, 8, 10])

corr_matrix = np.corrcoef(x, y)
correlation = corr_matrix[0, 1]

print(f"Correlation Coefficient (x, y): {correlation:.2f}")

49. Create a function that splits an array into multiple sub-arrays along a specified axis.

original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


In [ ]:
import numpy as np
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

product = np.dot(A, B)

print(f"Matrix Product (A dot B):\n{product}")
# Output: [[1*5+2*7, 1*6+2*8], [3*5+4*7, 3*6+4*8]] -> [[19, 22], [43, 50]]

50. Write a function that inserts and then deletes elements from a given array at specified indices.

original_array = np.array([1, 2, 3, 4, 5])

indices_to_insert = [2, 4]

values_to_insert = [10, 11]

indices_to_delete = [1, 3]

In [ ]:
import numpy as np
data = np.random.randint(10, 1001, size=50)

p10 = np.percentile(data, 10)
median = np.percentile(data, 50)
p90 = np.percentile(data, 90)

q1 = np.percentile(data, 25)
q3 = np.percentile(data, 75)

print(f"10th Percentile: {p10}")
print(f"50th Percentile (Median): {median}")
print(f"90th Percentile: {p90}")
print(f"First Quartile (Q1): {q1}")
print(f"Third Quartile (Q3): {q3}")

51. Create a NumPy array arr1 with random integers and another array arr2 with integers from 1 to 10. Perform element-wise addition between arr1 and arr2.

In [ ]:
import numpy as np
arr1 = np.random.randint(1, 10, size=10)
arr2 = np.arange(1, 11)

addition = arr1 + arr2
print(f"Arr1: {arr1}")
print(f"Arr2: {arr2}")
print(f"Addition: {addition}")

52. Generate a NumPy array arr1 with sequential integers from 10 to 1 and another array arr2 with integers from 1 to 10. Subtract arr2 from arr1 element-wise.

In [ ]:
import numpy as np
arr1 = np.arange(10, 0, -1) # [10, 9, 8, ..., 1]
arr2 = np.arange(1, 11)     # [1, 2, 3, ..., 10]

subtraction = arr1 - arr2
print(f"Subtraction (arr1 - arr2): {subtraction}")
# Output: [9, 7, 5, 3, 1, -1, -3, -5, -7, -9]

53. Create a NumPy array arr1 with random integers and another array arr2 with integers from 1 to 5. Perform element-wise multiplication between arr1 and arr2.

In [ ]:
import numpy as np
arr1 = np.random.randint(1, 10, size=5)
arr2 = np.arange(1, 6)

multiplication = arr1 * arr2
print(f"Arr1: {arr1}")
print(f"Arr2: {arr2}")
print(f"Multiplication: {multiplication}")

54. Generate a NumPy array arr1 with even integers from 2 to 10 and another array arr2 with integers from 1 to 5. Perform element-wise division of arr1 by arr2.

In [ ]:
import numpy as np
arr1 = np.arange(2, 11, 2) # [2, 4, 6, 8, 10]
arr2 = np.arange(1, 6)     # [1, 2, 3, 4, 5]

division = arr1 / arr2
print(f"Division (arr1 / arr2): {division}")
# Output: [2. 2. 2. 2. 2.]

55. Create a NumPy array arr1 with integers from 1 to 5 and another array arr2 with the same numbers reversed. Calculate the exponentiation of arr1 raised to the power of arr2 element-wise.

In [ ]:
import numpy as np
arr1 = np.arange(1, 6) # [1, 2, 3, 4, 5]
arr2 = arr1[::-1]      # [5, 4, 3, 2, 1]

exponentiation = np.power(arr1, arr2)
print(f"Arr1: {arr1}")
print(f"Arr2: {arr2}")
print(f"Exponentiation (arr1 ** arr2): {exponentiation}")
# Output: [  1 16 27 16  5] (1^5, 2^4, 3^3, 4^2, 5^1)

56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings. 86$arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello']).

In [ ]:
import numpy as np
def count_substring(arr, substring):
    counts = np.char.count(arr, substring)
    return np.sum(counts)

arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
count = count_substring(arr, 'hello')
print(f"Count of 'hello': {count}")

59. Write a function that concatenates strings in a NumPy array element-wise.

arr1 = np.array(['Hello', 'World'])

arr2 = np.array(['Open', 'AI'])

In [ ]:
import numpy as np
def extract_uppercase(arr):
    # Apply a function element-wise that filters uppercase chars from each string
    result = np.array([''.join(c for c in s if c.isupper()) for s in arr])
    return result

arr = np.array(['Hello', 'World', 'OpenAI'])
uppercase_chars = extract_uppercase(arr)
print(f"Extracted uppercase chars: {uppercase_chars}")
# Output: ['H' 'W' 'OAI']

60. Write a function that finds the length of the longest string in a NumPy array.

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])


In [ ]:
import numpy as np
def replace_substring(arr, old, new):
    return np.char.replace(arr, old, new)

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
replaced = replace_substring(arr, 'apple', 'orange')
print(f"Replaced array: {replaced}")

61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and
standard deviation of the dataset using NumPy's functions.

In [ ]:
import numpy as np
# Setting a seed for reproducible results in this example
np.random.seed(42)
dataset = np.random.randint(1, 1001, size=100)

mean = np.mean(dataset)
median = np.median(dataset)
variance = np.var(dataset)
std_dev = np.std(dataset)

print(f"Dataset Mean: {mean}")
print(f"Dataset Median: {median}")
print(f"Dataset Variance: {variance}")
print(f"Dataset Standard Deviation: {std_dev}")

62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset.

In [ ]:
import numpy as np
# Setting a seed for reproducible results in this example
np.random.seed(42)
data = np.random.uniform(1, 100, size=50)

percentile_25 = np.percentile(data, 25)
percentile_75 = np.percentile(data, 75)

print(f"25th Percentile: {percentile_25}")
print(f"75th Percentile: {percentile_75}")

63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's corrcoef function.

In [ ]:
import numpy as np
x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 6, 8, 10])

# np.corrcoef returns the correlation matrix
corr_matrix = np.corrcoef(x, y)
correlation = corr_matrix[0, 1]

print(f"Correlation Matrix:\n{corr_matrix}")
print(f"Correlation Coefficient (x, y): {correlation}")

64. Create two matrices and perform matrix multiplication using NumPy's dot function.

In [ ]:
import numpy as np
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

product = np.dot(A, B)

print(f"Matrix Product (A dot B):\n{product}")

65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiles.

In [ ]:
import numpy as np
# Setting a seed for reproducible results in this example
np.random.seed(42)
data = np.random.randint(10, 1001, size=50)

p10 = np.percentile(data, 10)
median = np.percentile(data, 50)
p90 = np.percentile(data, 90)

q1 = np.percentile(data, 25)
q3 = np.percentile(data, 75)

print(f"10th Percentile: {p10}")
print(f"50th Percentile (Median): {median}")
print(f"90th Percentile: {p90}")
print(f"First Quartile (Q1): {q1}")
print(f"Third Quartile (Q3): {q3}")

66. Create a NumPy array of integers and find the index of a specific element.

In [ ]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
target_value = 30

# np.where returns a tuple of arrays; [0] accesses the 1D array of indices
index = np.where(arr == target_value)[0]
print(f"Index of {target_value}: {index[0]}")

67. Generate a random NumPy array and sort it in ascending order.

In [ ]:
import numpy as np
random_arr = np.random.randint(0, 100, size=10)
print(f"Original array: {random_arr}")

sorted_arr = np.sort(random_arr)
print(f"Sorted array: {sorted_arr}")

68. Filter elements >20  in the given NumPy array.

arr = np.array([12, 25, 6, 42, 8, 30])


In [ ]:
import numpy as np
arr = np.array([12, 25, 6, 42, 8, 30])
filtered = arr[arr > 20]
print(f"Elements > 20: {filtered}")

69. Filter elements which are divisible by 3 from a given NumPy array.
arr = np.array([1, 5, 8, 12, 15])

In [ ]:
import numpy as np
arr = np.array([1, 5, 8, 12, 15])
filtered = arr[arr % 3 == 0]
print(f"Elements divisible by 3: {filtered}")

70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.

arr = np.array([10, 20, 30, 40, 50])


In [ ]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
filtered = arr[(arr >= 20) & (arr <= 40)]
print(f"Elements >= 20 and <= 40: {filtered}")

71. For the given NumPy array, check its byte order using the `dtype` attribute byteorder.

arr = np.array([1, 2, 3])


In [ ]:
import numpy as np
arr = np.array([1, 2, 3])
byte_order = arr.dtype.byteorder
print(f"Array byte order: {byte_order}")

72. For the given NumPy array, perform byte swapping in place using `byteswap()`.
arr = np.array([1, 2, 3], dtype=np.int32)


In [ ]:
import numpy as np
arr = np.array([1, 2, 3], dtype=np.int32)
print(f"Original array: {arr}, Byte order: {arr.dtype.byteorder}")

arr.byteswap(inplace=True)

print(f"Swapped array: {arr}, New byte order: {arr.dtype.byteorder}")

73. For the given NumPy array, swap its byte order without modifying the original array using `newbyteorder()`.

arr = np.array([1, 2, 3], dtype=np.int32)


In [ ]:
import numpy as np
arr = np.array([1, 2, 3], dtype=np.int32)

swapped_arr = arr.newbyteorder()

print(f"Original array byte order: {arr.dtype.byteorder}")
print(f"New array byte order: {swapped_arr.dtype.byteorder}")
print(f"Original array modified? {np.shares_memory(arr, swapped_arr)}")

74. For the given NumPy array and swap its byte order conditionally based on system endianness using `newbyteorder()`.

arr = np.array([1, 2, 3], dtype=np.int32)


In [ ]:
import numpy as np
arr = np.array([1, 2, 3], dtype=np.int32)

# Target the non-native byte order (e.g., '>' if native is '<')
opposite_order = '>' if np.dtype('=').byteorder == '<' else '<'
swapped_arr = arr.newbyteorder(opposite_order)

print(f"System native order: {np.dtype('=').byteorder}")
print(f"Conditionally swapped array order: {swapped_arr.dtype.byteorder}")

75. For the given NumPy array, check if byte swapping is necessary for the current system using `dtype` attribute `byteorder`.

arr = np.array([1, 2, 3], dtype=np.int32)

In [ ]:
import numpy as np
arr = np.array([1, 2, 3], dtype=np.int32)

is_non_native = arr.dtype.byteorder not in ('=', '|')

print(f"Array byte order is non-native (swapping needed): {is_non_native}")

76. Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.

In [ ]:
import numpy as np
arr1 = np.arange(1, 11)
copy_arr = arr1.copy() # Deep Copy

copy_arr[0] = 999

print(f"Original arr1[0]: {arr1[0]}")
print(f"Is arr1 modified? {arr1[0] != copy_arr[0]}")

77. Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.

In [ ]:
import numpy as np
matrix = np.random.randint(1, 10, size=(3, 3))

view_slice = matrix[0:2, 0:2] # Slice (creates a view)
view_slice[0, 0] = 99

print(f"Original matrix element (0, 0): {matrix[0, 0]}")
print(f"Was original matrix changed? {matrix[0, 0] == 99}")

78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice `view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.

In [ ]:
import numpy as np
array_a = np.arange(1, 13).reshape(4, 3)

view_b = array_a[1:3, :] # Slice (creates a view)
view_b += 5 # Broadcast addition

print(f"Original element at (1, 0) (was 4): {array_a[1, 0]}")
print(f"Was original array_a changed? {array_a[1, 0] == 9}")

79. Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view `reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it reflects changes in the original `orig_array`.

In [ ]:
import numpy as np
orig_array = np.arange(1, 9).reshape(2, 4)

reshaped_view = orig_array.view().reshape(4, 2)
reshaped_view[1, 0] = 99

# The element at reshaped_view[1, 0] corresponds to orig_array[0, 2]
print(f"Original element at (0, 2) (was 3): {orig_array[0, 2]}")
print(f"Original array changed? {orig_array[0, 2] == 99}")

80. Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.

In [ ]:
import numpy as np
data = np.random.randint(1, 10, size=(3, 4))

# Boolean indexing returns a copy
data_copy = data[data > 5]

if data_copy.size > 0:
    data_copy[0] = 999

# Check if the original array's first element > 5 is still the same
# We compare the value in the original array's index that was copied
original_element_idx = np.where(data > 5)

if original_element_idx[0].size > 0:
    first_modified_original_value = data[original_element_idx[0][0], original_element_idx[1][0]]
    print(f"Was original data modified? {first_modified_original_value != 999}")

81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them.

In [ ]:
import numpy as np
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

addition = A + B
subtraction = A - B

print(f"Addition (A + B):\n{addition}")
print(f"Subtraction (A - B):\n{subtraction}")

82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.

In [ ]:
import numpy as np
C = np.arange(1, 7).reshape(3, 2) # 3x2
D = np.arange(10, 18).reshape(2, 4) # 2x4

product = C @ D

print(f"Matrix Product (C @ D, 3x4):\n{product}")

83. Create a matrix `E` and find its transpose.

In [ ]:
import numpy as np
E = np.array([[1, 2, 3], [4, 5, 6]]) # 2x3 matrix

E_transpose = E.T

print(f"Transpose of E:\n{E_transpose}")

84. Generate a square matrix `F` and compute its determinant.

In [ ]:
import numpy as np
# A 2x2 matrix with non-zero determinant
F = np.array([[4, 6], [3, 8]])

determinant = np.linalg.det(F)

print(f"Determinant of F: {determinant:.2f}")

85. Create a square matrix `G` and find its inverse.

In [ ]:
import numpy as np
# A matrix with a non-zero determinant
G = np.array([[4, 6], [3, 8]])

G_inverse = np.linalg.inv(G)

print(f"Inverse of G:\n{G_inverse}")